---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: csi-hc-snapshot
  namespace: clusters-jparrill-hosted
spec:
  source:
    persistentVolumeClaimName: data-etcd-0
  volumeSnapshotClassName: csi-aws-vsc